### ISSUE TITLE
docker: Invalid containerPort: 3478：3478.

### ISSUE THREAD

**Issue by walle-z** [instrumentisto/coturn-docker-image#1] opened 2018-08-08 00:31 UTC
When I run this command "docker run -d -p 3478：3478            -v $（ pwd ） /my.conf:/etc/coturn/turnserver.conf        instrumentisto / coturn"
I got an error :docker: Invalid containerPort: 3478：3478.

**Comment by tyranron** [comment] 2018-08-08 04:03
@zhangguangfengz you should not specify a space between mapping ports. `-p 3478:3478` is correct, `-p 3478: 3478` is not.

The issue is not relevant to this Coturn Docker image, but rather to using Docker CLI. So I'm closing it. Please, use [official Docker CLI guide](https://docs.docker.com/engine/reference/commandline/cli/) to resolve your issue..

**Closed as completed by tyranron** 2018-08-08 04:03 UTC
Labels: question, wontfix
